backend/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  namespace :api do
    resources :events, only: [:index]
  end

  resources :events, only: %i[index new create edit update]

  root to: 'events#index'
end

backend/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable, :trackable
  # and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

backend/app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  # Validations.
  validates_presence_of :city, :organiser, :starts_on, :web

  # Returns all events ordered by event start descending.
  def self.list
    Event.order('starts_on DESC')
  end
end

backend/app/controllers/api/api_controller.rb
# frozen_string_literal: true

module API
  class APIController < ActionController::Base
  end
end

backend/app/controllers/api/events_controller.rb
# frozen_string_literal: true

module API
  class EventsController < APIController
    def index
      render json: Event.list
    end
  end
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

backend/app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @events = Event.list
  end

  def new
    @event = Event.new
  end

  def create
    Event.create(event_params)
    redirect_to events_path
  end

  def edit
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params
      .require(:event)
      .permit(:city, :description, :organiser, :reg, :starts_on, :title, :web)
  end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <div class="form-field">
    <%= f.label :title, class: "label" %>
    <%= f.text_field :title, required: true, class: "input" %>
  </div>
  <div class="form-field">
    <%= f.label :city, class: "label" %>
    <%= f.text_field :city, required: true, class: "input" %>
  </div>
  <div class="form-field">
    <%= f.label :description, class: "label" %>
    <%= f.text_area :description, class: "textarea" %>
  </div>
  <div class="form-field">
    <%= f.label :organiser, class: "label" %>
    <%= f.text_field :organiser, required: true, class: "input" %>
  </div>
  <div class="form-field">
    <%= f.label :starts_on, class: "label" %>
    <%= f.date_field :starts_on, required: true, class: "input" %>
  </div>
  <div class="form-field">
    <%= f.label :web, class: "label" %>
    <%= f.url_field :web, required: true, class: "input" %>
  </div>
  <div class="form-field">
    <%= f.label :reg, class: "label" %>
    <%= f.url_field :reg, class: "input" %>
  </div>
  <div class="form-submit">
    <%= f.submit class: "button is-primary" %>
  </div>
<% end %>

backend/app/views/events/edit.html.erb
<h2 class="title">Edit event</h2>

<%= render "form" %>

backend/app/views/events/index.html.erb
<h2 class="title">Events</h2>
<p>
  <%= link_to t('.add_event'), new_event_path, class: "button is-primary" %>
</p>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Starts on</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| -%>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.starts_on %></td>
    </tr>
    <% end -%>
  </tbody>
</table>

backend/app/views/events/new.html.erb
<h2 class="title">New event</h2>

<%= render "form" %>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Rundb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="description" content="<%= t('.meta_description') %>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          rundb
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarMain">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarMain" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="/">
            Home
          </a>

          <a class="navbar-item" href="/events">
            Events
          </a>
        </div>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>